[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# --- Web framework ---
axum = { version = "0.8", features = ["macros"] }
axum-extra = { version = "0.10", features = ["typed-header"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["cors"] }
tokio = { version = "1", features = ["full"] }

# --- GraphQL ---
async-graphql = "7"
async-graphql-axum = "7"

# --- Database ---
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "postgres",
    "macros",
    "uuid",
    "chrono",
] }

# --- Auth & Security ---
jsonwebtoken = { version = "10", features = ["rust_crypto"] }
bcrypt = "0.17"
headers = "0.4"


# --- Utilities ---
dotenvy = "0.15"
anyhow = "1.0"
serde = { version = "1", features = ["derive"] }
chrono = "0.4.42"
uuid = { version = "1.1", features = ["v4"] }
sha2 = "0.10.9"
regex = "1.11.3"
